In [83]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

In [84]:
data = pd.read_csv('iris.csv')

In [85]:
data.sample(20)

sepal_length  sepal_width  petal_length  petal_width             Iris
149           5.9          3.0           5.1          1.8   Iris-virginica
137           6.4          3.1           5.5          1.8   Iris-virginica
48            5.3          3.7           1.5          0.2      Iris-setosa
37            4.9          3.1           1.5          0.1      Iris-setosa
128           6.4          2.8           5.6          2.1   Iris-virginica
19            5.1          3.8           1.5          0.3      Iris-setosa
38            4.4          3.0           1.3          0.2      Iris-setosa
0             5.1          3.5           1.4          0.2      Iris-setosa
50            7.0          3.2           4.7          1.4  Iris-versicolor
110           6.5          3.2           5.1          2.0   Iris-virginica
13            4.3          3.0           1.1          0.1      Iris-setosa
109           7.2          3.6           6.1          2.5   Iris-virginica
23            5.1          3.3           1.7          0.5      Iris-setosa
30            4.8          3.1           1.6          0.2      Iris-setosa
144           6.7          3.3           5.7          2.5   Iris-virginica
98            5.1          2.5           3.0          1.1  Iris-versicolor
18            5.7          3.8           1.7          0.3      Iris-setosa
46            5.1          3.8           1.6          0.2      Iris-setosa
9             4.9          3.1           1.5          0.1      Iris-setosa
116           6.5          3.0           5.5          1.8   Iris-virginica

In [86]:
data.info

<bound method DataFrame.info of      sepal_length  sepal_width  petal_length  petal_width            Iris
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]>

In [87]:
data = pd.DataFrame(data=iris.data, columns=iris.feature_names)

In [88]:
data.shape

(150, 4)

In [89]:
data .describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [90]:
data['Iris'] = iris.target

In [91]:
data['Iris'].value_counts()

0    50
1    50
2    50
Name: Iris, dtype: int64

In [92]:
label_encoder = LabelEncoder()

In [93]:
data['Iris'] = label_encoder.fit_transform(data['Iris'])

In [94]:
data.groupby('Iris').mean()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
Iris                                                                          
0                 5.006             3.428              1.462             0.246
1                 5.936             2.770              4.260             1.326
2                 6.588             2.974              5.552             2.026

In [95]:
x = data.drop(columns='Iris', axis=1)
y = data['Iris']

In [96]:
print(x)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]


In [97]:
print(y)

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Iris, Length: 150, dtype: int64


In [98]:
scaler = StandardScaler()

In [99]:
scaler.fit(x)

StandardScaler()

In [100]:
standardized_data = scaler.transform(x)

In [101]:
print(standardized_data)

[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

In [102]:
x = standardized_data
y = data['Iris']

In [103]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1, random_state=2)

In [104]:
print(x.shape,x_train.shape,x_test.shape)

(150, 4) (135, 4) (15, 4)


In [105]:
classifier = svm.SVC(kernel='linear')

In [106]:
classifier.fit(x_train, y_train)

SVC(kernel='linear')

In [107]:
x_train_prediction = classifier.predict(x_train)
train_data_accuracy = accuracy_score(x_train_prediction, y_train)  # Use y_train here, not y_test

print('Accuracy on training data:', train_data_accuracy)


Accuracy on training data: 0.9703703703703703


In [108]:
x_new_data = np.array([[6.3,2.3,4.4,1.3]])

In [109]:
x_new_scaled = scaler.transform(x_new_data)
new_data_prediction = classifier.predict(x_new_scaled)

C:\ProgramData\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [110]:
Iris = "Iris-setosa"
virginica = "Iris-virginica"

if new_data_prediction[0] == Iris:
    print("The object is an Iris-setosa")
elif new_data_prediction[0] == virginica:
    print("The object is an Iris-virginica")
else:
    print("The object is an Iris-versicolor")


The object is an Iris-versicolor


In [111]:
y_train

54     1
41     0
96     1
144    2
89     1
      ..
75     1
43     0
22     0
72     1
15     0
Name: Iris, Length: 135, dtype: int64

In [112]:
bins = np.linspace(min(y_train), max(y_train), 4)
y_train_binned = np.digitize(y_train, bins) - 1


In [117]:
svc = SVC(kernel='linear')
svc.fit(x_train, y_train)


SVC(kernel='linear')

In [118]:
with open('model.pkl', 'wb') as model_file:
    pickle.dump(svc, model_file)

print("Model saved successfully!")

Model saved successfully!
